trigger:
  - main

schedules:
  - cron: '30 23 * * *'
    displayName: Monday Playwright Test
    branches:
      include:
        - main
    always: true

pool:
  name: "OpenCart-Window-Pool"

steps:
  - script: |
      node --version
      npm --version
    displayName: "Check Node.js and npm"

  - script: npm ci
    displayName: "Install dependencies"

  - script: npx playwright install
    displayName: "Install Playwright browsers"

  - script: npx playwright test
    displayName: "Run all Playwright tests"
    env:
      CI: "true"
      BASE_URL: "http://localhost/opencart/upload/"

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "test-results/results.xml"
      failTaskOnFailedTests: true
      testRunTitle: "Playwright Test"

  - task: PublishAllureReport@2
    displayName: "Generate and Publish Allure Report"
    condition: succeededOrFailed()
    inputs:
      testResultsDir: "allure-results"
      reportName: "Playwright Allure Report"

  - task: PublishPipelineArtifact@1
    displayName: "Publish Playwright HTML Report"
    inputs:
      targetPath: "playwright-report"
      artifact: "playwright-report"
      publishLocation: "pipeline"

  - task: PublishPipelineArtifact@1
    displayName: "Publish Playwright HTML Report"
    inputs:
      targetPath: "playwright-report"
      artifact: "playwright-report"
      publishLocation: "pipeline"
  
  - powershell: |
      node scripts/send-report-email.js
    displayName: "Send Playwright Report Email"
    condition: succeededOrFailed()
    env:
      BREVO_SMTP_HOST: $(BREVO_SMTP_HOST)
      BREVO_SMTP_PORT: $(BREVO_SMTP_PORT)
      BREVO_SMTP_USER: $(BREVO_SMTP_USER)
      BREVO_SMTP_KEY: $(BREVO_SMTP_KEY)
      EMAIL_FROM: $(EMAIL_FROM)
      EMAIL_TO: $(EMAIL_TO)

      BUILD_STATUS: $(Agent.JobStatus)
      BUILD_COLLECTION_URI: $(System.CollectionUri)
      BUILD_PROJECT: $(System.TeamProject)
      BUILD_ID: $(Build.BuildId)
      BUILD_DEFINITION_NAME: $(Build.DefinitionName)
      BUILD_NUMBER: $(Build.BuildNumber)
