trigger:
  - main

pool:
  name: 'OpenCart-Mac-Pool'

steps:

  - script: |
      node --version
      npm --version
    displayName: 'Check Node.js and npm'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install
    displayName: 'Install Playwright browsers'

  - script: npx playwright test
    displayName: 'Run all Playwright tests'
    env:
      CI: 'true'
      BASE_URL: 'http://localhost/opencart/upload/'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test-results/results.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'Playwright Test'
  
  