trigger:
  - main

pool:
  name: 'OpenCart-Mac-Pool'

steps:

  - script: |
      node --version
      npm --version
    displayName: 'Check Node.js and npm'

  - script: npm ci
    displayName: 'Install dependencies'

  - script: npx playwright install
    displayName: 'Install Playwright browsers'

  - script: npm install -g allure-commandline
    displayName: 'Install Allure CLI'

  - script: npx playwright test
    displayName: 'Run all Playwright tests'
    env:
      CI: 'true'
      BASE_URL: 'http://localhost/opencart/upload/'

  - script: allure generate allure-results --clean -o allure-report
    displayName: 'Generate Allure Report'
    condition: succeededOrFailed()   

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'test-results/results.xml'
      failTaskOnFailedTests: true
      testRunTitle: 'Playwright Test'

  - task: PublishPipelineArtifact@1
    condition: succeededOrFailed()
    inputs:
      targetPath: 'playwright-report'
      artifact: 'playwright-report'
      publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'allure-report'
      artifact: 'allure-report'
      publishLocation: 'pipeline'

 


  
